### PR TITLE
ci: update build script for both linux and win

### PR DESCRIPTION
**Pull request by dabrain34**

### CODE REVIEW

**Comment by dabrain34** [comment]
@zlatinski

**Review by zlatinski — APPROVED** [review]
Looks good - thank you!

**Review by zlatinski — APPROVED** [review]
Looks good - thank you!

**Review by zlatinski — APPROVED** [review]
Looks good - thank you!

**Review by zlatinski — APPROVED** [review]
Looks good - thank you!

**Review by zlatinski — APPROVED** [review]
Looks good - thank you!

**Review by zlatinski — APPROVED** [review]
Looks good - thank you!

**Pull request merged**
